% File: main_simulation.m
% Course: MMM 5162 Modelling and Simulation
% Project: Mini Project 1 - Track MR
% Purpose:
%   Simulate a two-link robot pick cycle and perform
%   a cycle-time parameter study.
%
% Student-specific number: S = 18
%
% Outputs:
%   - End-effector path
%   - Joint angle plots
%   - Joint angular velocity plots
%   - Cycle-time comparison plot
%   - Numerical results table
%   - CSV results file
%
% Notes:
%   All angles are handled internally in radians.

clear;
clc;
close all;


%% --------------------------------------------------------
% 1. PROJECT FOLDERS
% ---------------------------------------------------------

% Find the folder containing this MATLAB file
code_folder = fileparts(mfilename('fullpath'));

% Project root is one level above the code folder
project_root = fileparts(code_folder);

% Define results folders
figures_folder = fullfile( ...
    project_root, ...
    'results', ...
    'figures' ...
);

tables_folder = fullfile( ...
    project_root, ...
    'results', ...
    'tables' ...
);

% Create folders automatically if they do not exist
if ~exist(figures_folder, 'dir')
    mkdir(figures_folder);
end

if ~exist(tables_folder, 'dir')
    mkdir(tables_folder);
end


%% --------------------------------------------------------
% 2. STUDENT-SPECIFIC PARAMETERS
% ---------------------------------------------------------

S = 18;

L1 = 0.380 + 0.005 * S;
L2 = 0.300 + 0.004 * S;

q1_start_deg = 20 + S;
q1_end_deg   = 75 - 0.5 * S;

q2_start_deg = -55 + 0.8 * S;
q2_end_deg   = 15 + 0.5 * S;

T_nominal = 2.40 + 0.04 * S;


%% --------------------------------------------------------
% 3. CONVERT DEGREES TO RADIANS
% ---------------------------------------------------------

q1_start = deg2rad(q1_start_deg);
q1_end   = deg2rad(q1_end_deg);

q2_start = deg2rad(q2_start_deg);
q2_end   = deg2rad(q2_end_deg);


%% --------------------------------------------------------
% 4. PARAMETER STUDY SETTINGS
% ---------------------------------------------------------

cycle_factors = [0.8, 1.0, 1.2];

number_of_cases = length(cycle_factors);

% Preallocate result vectors
cycle_times = zeros(number_of_cases, 1);

max_q1_speed = zeros(number_of_cases, 1);
max_q2_speed = zeros(number_of_cases, 1);

path_lengths = zeros(number_of_cases, 1);

max_ee_speed = zeros(number_of_cases, 1);

start_x = zeros(number_of_cases, 1);
start_y = zeros(number_of_cases, 1);

end_x = zeros(number_of_cases, 1);
end_y = zeros(number_of_cases, 1);


%% --------------------------------------------------------
% 5. STORAGE FOR BASELINE CASE
% ---------------------------------------------------------

baseline_t = [];
baseline_q1 = [];
baseline_q2 = [];

baseline_q1_dot = [];
baseline_q2_dot = [];

baseline_x = [];
baseline_y = [];


%% --------------------------------------------------------
% 6. RUN PARAMETER STUDY
% ---------------------------------------------------------

for i = 1:number_of_cases

    % Current cycle-time factor
    factor = cycle_factors(i);

    % Current cycle time
    T = factor * T_nominal;

    % Store cycle time
    cycle_times(i) = T;

    % Create 1001 equally spaced simulation points
    t = linspace(0, T, 1001);

    % -----------------------------------------------------
    % Run robot model
    % -----------------------------------------------------

    [q1, q2, q1_dot, q2_dot, x, y] = robot_model( ...
        t, ...
        T, ...
        L1, ...
        L2, ...
        q1_start, ...
        q1_end, ...
        q2_start, ...
        q2_end ...
    );

    % -----------------------------------------------------
    % 7. PERFORMANCE MEASURES
    % -----------------------------------------------------

    max_q1_speed(i) = max(abs(q1_dot));

    max_q2_speed(i) = max(abs(q2_dot));

    % Difference between consecutive x and y positions
    dx = diff(x);
    dy = diff(y);

    % Total end-effector path length
    path_lengths(i) = sum( ...
        sqrt(dx.^2 + dy.^2) ...
    );

    % Numerical end-effector velocity
    x_dot = gradient(x, t);
    y_dot = gradient(y, t);

    ee_speed = sqrt( ...
        x_dot.^2 + y_dot.^2 ...
    );

    max_ee_speed(i) = max(ee_speed);

    % Start coordinates
    start_x(i) = x(1);
    start_y(i) = y(1);

    % End coordinates
    end_x(i) = x(end);
    end_y(i) = y(end);


    %% ----------------------------------------------------
    % 8. AUTOMATIC VERIFICATION CHECKS
    % -----------------------------------------------------

    tolerance = 1e-10;

    assert( ...
        abs(q1(1) - q1_start) < tolerance, ...
        'Joint 1 initial angle check failed.' ...
    );

    assert( ...
        abs(q1(end) - q1_end) < tolerance, ...
        'Joint 1 final angle check failed.' ...
    );

    assert( ...
        abs(q2(1) - q2_start) < tolerance, ...
        'Joint 2 initial angle check failed.' ...
    );

    assert( ...
        abs(q2(end) - q2_end) < tolerance, ...
        'Joint 2 final angle check failed.' ...
    );

    assert( ...
        abs(q1_dot(1)) < tolerance, ...
        'Joint 1 initial velocity check failed.' ...
    );

    assert( ...
        abs(q1_dot(end)) < tolerance, ...
        'Joint 1 final velocity check failed.' ...
    );

    assert( ...
        abs(q2_dot(1)) < tolerance, ...
        'Joint 2 initial velocity check failed.' ...
    );

    assert( ...
        abs(q2_dot(end)) < tolerance, ...
        'Joint 2 final velocity check failed.' ...
    );


    %% ----------------------------------------------------
    % 9. SAVE BASELINE CASE
    % -----------------------------------------------------

    if abs(factor - 1.0) < tolerance

        baseline_t = t;

        baseline_q1 = q1;
        baseline_q2 = q2;

        baseline_q1_dot = q1_dot;
        baseline_q2_dot = q2_dot;

        baseline_x = x;
        baseline_y = y;

    end

end


%% --------------------------------------------------------
% 10. CREATE RESULTS TABLE
% ---------------------------------------------------------

case_names = { ...
    '0.8T'; ...
    '1.0T'; ...
    '1.2T' ...
};

results_table = table( ...
    case_names, ...
    cycle_times, ...
    max_q1_speed, ...
    max_q2_speed, ...
    path_lengths, ...
    max_ee_speed, ...
    start_x, ...
    start_y, ...
    end_x, ...
    end_y, ...
    'VariableNames', { ...
        'Case', ...
        'CycleTime_s', ...
        'Max_q1_dot_rad_s', ...
        'Max_q2_dot_rad_s', ...
        'PathLength_m', ...
        'MaxEndEffectorSpeed_m_s', ...
        'StartX_m', ...
        'StartY_m', ...
        'EndX_m', ...
        'EndY_m' ...
    } ...
);


%% --------------------------------------------------------
% 11. SAVE RESULTS TABLE AS CSV
% ---------------------------------------------------------

results_file = fullfile( ...
    tables_folder, ...
    'parameter_study_results_matlab.csv' ...
);

writetable( ...
    results_table, ...
    results_file ...
);


%% --------------------------------------------------------
% 12. BASELINE END-EFFECTOR PATH
% ---------------------------------------------------------

figure;

plot( ...
    baseline_x, ...
    baseline_y, ...
    'LineWidth', 2 ...
);

hold on;

scatter( ...
    baseline_x(1), ...
    baseline_y(1), ...
    50, ...
    'filled' ...
);

scatter( ...
    baseline_x(end), ...
    baseline_y(end), ...
    50, ...
    'filled' ...
);

xlabel('x Position (m)');
ylabel('y Position (m)');

title('Baseline End-Effector Path');

legend( ...
    'End-Effector Path', ...
    'Start', ...
    'End', ...
    'Location', ...
    'best' ...
);

grid on;
axis equal;

exportgraphics( ...
    gcf, ...
    fullfile( ...
        figures_folder, ...
        'baseline_end_effector_path_matlab.png' ...
    ), ...
    'Resolution', ...
    300 ...
);


%% --------------------------------------------------------
% 13. BASELINE JOINT ANGLES
% ---------------------------------------------------------

figure;

plot( ...
    baseline_t, ...
    rad2deg(baseline_q1), ...
    'LineWidth', 1.5 ...
);

hold on;

plot( ...
    baseline_t, ...
    rad2deg(baseline_q2), ...
    'LineWidth', 1.5 ...
);

xlabel('Time (s)');
ylabel('Joint Angle (deg)');

title('Baseline Joint Angles');

legend( ...
    'Joint 1', ...
    'Joint 2', ...
    'Location', ...
    'best' ...
);

grid on;

exportgraphics( ...
    gcf, ...
    fullfile( ...
        figures_folder, ...
        'baseline_joint_angles_matlab.png' ...
    ), ...
    'Resolution', ...
    300 ...
);


%% --------------------------------------------------------
% 14. BASELINE JOINT VELOCITIES
% ---------------------------------------------------------

figure;

plot( ...
    baseline_t, ...
    baseline_q1_dot, ...
    'LineWidth', 1.5 ...
);

hold on;

plot( ...
    baseline_t, ...
    baseline_q2_dot, ...
    'LineWidth', 1.5 ...
);

xlabel('Time (s)');

ylabel( ...
    'Joint Angular Velocity (rad/s)' ...
);

title( ...
    'Baseline Joint Angular Velocities' ...
);

legend( ...
    'Joint 1', ...
    'Joint 2', ...
    'Location', ...
    'best' ...
);

grid on;

exportgraphics( ...
    gcf, ...
    fullfile( ...
        figures_folder, ...
        'baseline_joint_velocities_matlab.png' ...
    ), ...
    'Resolution', ...
    300 ...
);


%% --------------------------------------------------------
% 15. PARAMETER-STUDY COMPARISON PLOT
% ---------------------------------------------------------

figure;

plot( ...
    cycle_factors, ...
    max_q1_speed, ...
    '-o', ...
    'LineWidth', ...
    1.5 ...
);

hold on;

plot( ...
    cycle_factors, ...
    max_q2_speed, ...
    '-o', ...
    'LineWidth', ...
    1.5 ...
);

xlabel('Cycle-Time Factor');

ylabel( ...
    'Maximum Joint Speed (rad/s)' ...
);

title( ...
    'Effect of Cycle Time on Maximum Joint Speed' ...
);

legend( ...
    'Max |q1 dot|', ...
    'Max |q2 dot|', ...
    'Location', ...
    'best' ...
);

xticks(cycle_factors);

xticklabels({ ...
    '0.8T', ...
    'T', ...
    '1.2T' ...
});

grid on;

exportgraphics( ...
    gcf, ...
    fullfile( ...
        figures_folder, ...
        'cycle_time_speed_comparison_matlab.png' ...
    ), ...
    'Resolution', ...
    300 ...
);


%% --------------------------------------------------------
% 16. PRINT PROJECT SUMMARY
% ---------------------------------------------------------

fprintf('\n');
fprintf('MINI PROJECT 1 - MR TRACK - MATLAB\n');
fprintf('---------------------------------\n');

fprintf( ...
    'Student number S = %d\n', ...
    S ...
);

fprintf( ...
    'L1 = %.3f m\n', ...
    L1 ...
);

fprintf( ...
    'L2 = %.3f m\n', ...
    L2 ...
);

fprintf( ...
    'q1 start = %.1f deg\n', ...
    q1_start_deg ...
);

fprintf( ...
    'q1 end   = %.1f deg\n', ...
    q1_end_deg ...
);

fprintf( ...
    'q2 start = %.1f deg\n', ...
    q2_start_deg ...
);

fprintf( ...
    'q2 end   = %.1f deg\n', ...
    q2_end_deg ...
);

fprintf( ...
    'Nominal cycle time = %.3f s\n', ...
    T_nominal ...
);

fprintf('\n');
fprintf('Parameter Study Results:\n');
fprintf('------------------------\n');

disp(results_table);

fprintf('\n');
fprintf('Automatic verification checks passed.\n');

fprintf('\n');
fprintf('Results saved to:\n');
fprintf('%s\n', fullfile(project_root, 'results'));